# External libs
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler

class RoutesDistancer:

    def __init__(self, df):
        self.cols = [
            # "quality",
            # "main_waypoint_id",
            "elevation_min",
            "elevation_max",
            "height_diff_up",
            "height_diff_down",
            "route_length",
            "difficulties_height",
            "height_diff_access",
            "height_diff_difficulties",
            "lift_access",
            "ski_rating",
            "ski_exposition",
            "labande_ski_rating",
            "labande_global_rating",
            "global_rating",
            "engagement_rating",
            "risk_rating",
            "equipment_rating",
            "ice_rating",
            "mixed_rating",
            # "geom",
            "glacier_gear_crampons_req",
            "glacier_gear_crampons_spring",
            "glacier_gear_glacier_crampons",
            "glacier_gear_glacier_safety_gear",
            "glacier_gear_no",
            "activities_hiking",
            "activities_ice_climbing",
            "activities_mountain_climbing",
            "activities_rock_climbing",
            "activities_skitouring",
            "activities_snow_ice_mixed",
            "activities_snowshoeing",
            "activities_via_ferrata",
            "activities_mountain_biking",
            "durations_mean",
            "route_types_expedition",
            "route_types_loop",
            "route_types_loop_hut",
            "route_types_return_same_way",
            "route_types_traverse",
            "route_types_raid",
            "orientations_E",
            "orientations_N",
            "orientations_NE",
            "orientations_NW",
            "orientations_S",
            "orientations_SE",
            "orientations_SW",
            "orientations_W",
            "configuration_corridor",
            "configuration_edge",
            "configuration_face",
            "configuration_glacier",
            "configuration_goulotte",
            "configuration_pillar",
            "rock_types_basalte",
            "rock_types_calcaire",
            "rock_types_conglomerat",
            "rock_types_gneiss",
            "rock_types_granit",
            "rock_types_gres",
            "rock_types_migmatite",
            "rock_types_mollasse_calcaire",
            "rock_types_pouding",
            "rock_types_quartzite",
            "rock_types_schiste",
            # "country_Argentine",
            # "country_Canada",
            # "country_Chine",
            # "country_Espagne",
            # "country_France",
            # "country_Géorgie",
            # "country_Islande",
            # "country_Italie",
            # "country_Kazakhstan",
            # "country_Kirghizstan",
            # "country_Népal",
            # "country_Pérou",
            # "country_Slovénie",
            # "country_Suisse",
            # "admin_limits_Alpes-Maritimes",
            # "admin_limits_Alpes-de-Haute-Provence",
            # "admin_limits_Ariège",
            # "admin_limits_Bouches-du-Rhône",
            # "admin_limits_Canton de Berne",
            # "admin_limits_Canton de Fribourg",
            # "admin_limits_Canton de Glaris",
            # "admin_limits_Canton de Saint-Gall",
            # "admin_limits_Canton de Schwyz",
            # "admin_limits_Colombie-Britannique",
            # "admin_limits_Doubs",
            # "admin_limits_Drôme",
            # "admin_limits_Gard",
            # "admin_limits_Grisons",
            # "admin_limits_Haute-Garonne",
            # "admin_limits_Haute-Savoie",
            # "admin_limits_Hautes-Alpes",
            # "admin_limits_Hautes-Pyrénées",
            # "admin_limits_Hérault",
            # "admin_limits_Isère",
            # "admin_limits_Loire",
            # "admin_limits_Province autonome de Bolzano",
            # "admin_limits_Province autonome de Trente",
            # "admin_limits_Province de Bergame",
            # "admin_limits_Province de Biella",
            # "admin_limits_Province de Brescia",
            # "admin_limits_Province de Coni",
            # "admin_limits_Province de Huesca",
            # "admin_limits_Province de Lecco",
            # "admin_limits_Province de Lleida",
            # "admin_limits_Province de Sondrio",
            # "admin_limits_Province de Ségovie",
            # "admin_limits_Province de Turin",
            # "admin_limits_Province de Verceil",
            # "admin_limits_Province du Verbano-Cusio-Ossola",
            # "admin_limits_Pyrénées-Atlantiques",
            # "admin_limits_Pyrénées-Orientales",
            # "admin_limits_Savoie",
            # "admin_limits_Tessin",
            # "admin_limits_Uri",
            # "admin_limits_Valais",
            # "admin_limits_Vallée d'Aoste",
            # "admin_limits_Var",
            # "admin_limits_Vaucluse",
            # "admin_limits_Vaud",
            # "admin_limits_Xinjiang",
            # "range_Adamello",
            # "range_Alpes Bergamasques",
            # "range_Alpes Bernoises",
            # "range_Alpes Glaronaises",
            # "range_Alpes Grées - Charbonnel",
            # "range_Alpes Kamnik-Savinja et Karavanke",
            # "range_Alpes Ligures",
            # "range_Alpes Tessinoises - Conches - Goms",
            # "range_Alpes Uranaises",
            # "range_Alpes Vaudoises",
            # "range_Bauges",
            # "range_Beaufortain",
            # "range_Belledonne",
            # "range_Bigorre - Ordesa",
            # "range_Bornes - Aravis",
            # "range_Béarn - Balaïtous - Partacua",
            # "range_Bündner Oberland - Adula - Tessin E",
            # "range_Calanques",
            # "range_Cerces - Thabor - Mont-Cenis",
            # "range_Chablais",
            # "range_Chartreuse",
            # "range_Couserans - Aran N",
            # "range_Dolomites centrales",
            # "range_Dévoluy",
            # "range_Engadine - Disgrazia",
            # "range_Genevois - Jura S",
            # "range_Grand Paradis",
            # "range_Grandes Rousses - Arves",
            # "range_Grisons centraux",
            # "range_Haut Giffre - Aiguilles Rouges - Fiz",
            # "range_Haute Ariège - Andorre",
            # "range_Jura",
            # "range_Lauzière - Cheval Noir",
            # "range_Luberon - Baronnies - Saoû",
            # "range_Luchon - Posets - Maladeta - Aigüestortes",
            # "range_Mercantour - Argentera",
            # "range_Mont-Blanc",
            # "range_Ortles",
            # "range_Patagonie S",
            # "range_Pelat - Préalpes de Castellane",
            # "range_Provence",
            # "range_Préalpes Fribourgeoises - Bernoises",
            # "range_Préalpes de Digne",
            # "range_Puigmal - Canigou - Albères",
            # "range_Queyras N - Briançonnais - Alpes Cottiennes",
            # "range_Queyras S - Parpaillon - Ubaye - Orrenaye",
            # "range_Sierra de Guadarrama",
            # "range_Sierras aragonaises",
            # "range_Taillefer - Armet",
            # "range_Toggenburg - Appenzell",
            # "range_Valais E - Alpes Pennines E",
            # "range_Valais W - Alpes Pennines W",
            # "range_Vanoise",
            # "range_Vercors",
            # "range_Écrins",
            "is_refuge",
            "is_cabane",
            "is_arete",
            "is_glacier",
            "is_couloir",
            "is_goulotte"
        ]
        self.df = df.copy()

        self.__fillna()

    def __fillna(self):
        for col in self.cols:
            if self.df[col].isna().any():
                self.df[col] = self.df[col].fillna(self.df[col].median())

    def get_sim_routes_from_route(self, route_id):
        selected_index = self.df[self.df["document_id"] == route_id].index
        other_index = self.df[~(self.df["document_id"] == route_id)].index

        scaler = StandardScaler()
        scaler = scaler.fit(self.df[self.cols])
        scaled_data = scaler.transform(self.df[self.cols])

        similary_matrix = cosine_similarity(scaled_data[selected_index], scaled_data[other_index])

        self.df.loc[selected_index, "SUGGESTION"] = 1
        self.df.loc[other_index, "SUGGESTION"] = similary_matrix.max(axis=0)

        sim_routes = self.df.sort_values("SUGGESTION", ascending=False).loc[(self.df["SUGGESTION"] < 1), ["cooked_title", "link", "SUGGESTION"]].head(30)

        return sim_routes.to_markdown(index=False)